# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.cache/wt [current_project]
set_property parent.project_path C:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.srcs/sources_1/imports/Downloads/d_latch.vhd
  C:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.srcs/sources_1/new/filter.vhd
  C:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.srcs/sources_1/imports/Downloads/add_pixels.vhd
}
read_ip -quiet C:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.srcs/sources_1/ip/fifo/fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.srcs/sources_1/ip/fifo/fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Firmin/Documents/fpga-2d-filter/fpga-2d-filter.srcs/sources_1/ip/fifo/fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top filter -part xc7a100tcsg324-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef filter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file filter_utilization_synth.rpt -pb filter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
